-- Migration 007: Story State Board and Session Chat Integration
-- DM tracking board for who/what/when/where/why/how during sessions
-- Chat session auto-creation and history archival

-- Story state board - tracks campaign/session narrative state
CREATE TABLE IF NOT EXISTS state.story_state (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID NOT NULL REFERENCES state.campaigns(id) ON DELETE CASCADE,
    session_id UUID REFERENCES state.sessions(id) ON DELETE SET NULL,

    -- WHERE - Current location context
    current_location TEXT,
    location_details JSONB DEFAULT '{}',

    -- WHEN - In-game time tracking
    game_time TEXT,  -- e.g., "Day 3, Evening" or "Year 1423, Month of Frost, 15th day"
    game_time_details JSONB DEFAULT '{}',

    -- WHO - Active participants
    active_npcs JSONB DEFAULT '[]',  -- [{id, name, disposition, notes}]
    party_status JSONB DEFAULT '{}',  -- {morale, resources, conditions}

    -- WHAT - Current objectives and events
    active_quests JSONB DEFAULT '[]',  -- [{id, name, status, notes}]
    recent_events JSONB DEFAULT '[]',  -- [{timestamp, description, importance}]

    -- WHY - Motivations and plot threads
    plot_threads JSONB DEFAULT '[]',  -- [{id, name, status, notes}]
    party_goals JSONB DEFAULT '[]',  -- [{goal, priority, progress}]

    -- HOW - Resources and methods
    key_items JSONB DEFAULT '[]',  -- [{name, description, location}]
    party_resources JSONB DEFAULT '{}',  -- {gold, supplies, etc.}

    -- DM Notes
    dm_notes TEXT,
    dm_private_notes TEXT,  -- Hidden from players

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID REFERENCES state.principals(id)
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS idx_story_state_campaign ON state.story_state(campaign_id);
CREATE INDEX IF NOT EXISTS idx_story_state_session ON state.story_state(session_id);

-- Story state history - tracks changes over time for session replay
CREATE TABLE IF NOT EXISTS state.story_state_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    story_state_id UUID NOT NULL REFERENCES state.story_state(id) ON DELETE CASCADE,
    session_id UUID REFERENCES state.sessions(id) ON DELETE SET NULL,

    -- Snapshot of state at this point
    state_snapshot JSONB NOT NULL,

    -- What changed
    change_type TEXT NOT NULL CHECK (change_type IN (
        'LOCATION_CHANGE', 'TIME_ADVANCE', 'NPC_UPDATE', 'QUEST_UPDATE',
        'EVENT_LOGGED', 'ITEM_UPDATE', 'RESOURCE_CHANGE', 'NOTE_UPDATE', 'OTHER'
    )),
    change_description TEXT,

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES state.principals(id)
);

CREATE INDEX IF NOT EXISTS idx_story_history_state ON state.story_state_history(story_state_id);
CREATE INDEX IF NOT EXISTS idx_story_history_session ON state.story_state_history(session_id);

-- Session archive table for storing completed/archived sessions
CREATE TABLE IF NOT EXISTS state.session_archives (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    original_session_id UUID NOT NULL,
    campaign_id UUID NOT NULL REFERENCES state.campaigns(id) ON DELETE CASCADE,

    -- Session metadata
    session_name TEXT,
    session_number INT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,

    -- Archived chat history
    chat_history JSONB DEFAULT '[]',  -- Full chat log

    -- Final story state snapshot
    final_story_state JSONB DEFAULT '{}',

    -- Summary generated by DM or AI
    session_summary TEXT,
    key_moments JSONB DEFAULT '[]',  -- [{timestamp, description, significance}]

    -- Archive metadata
    archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_by UUID REFERENCES state.principals(id),
    archive_reason TEXT CHECK (archive_reason IN ('COMPLETED', 'DELETED', 'ABANDONED', 'MERGED'))
);

CREATE INDEX IF NOT EXISTS idx_session_archives_campaign ON state.session_archives(campaign_id);
CREATE INDEX IF NOT EXISTS idx_session_archives_original ON state.session_archives(original_session_id);

-- Add chat_session_id to sessions to track associated chat
ALTER TABLE state.sessions ADD COLUMN IF NOT EXISTS chat_started_at TIMESTAMPTZ;
ALTER TABLE state.sessions ADD COLUMN IF NOT EXISTS chat_last_activity TIMESTAMPTZ;
ALTER TABLE state.sessions ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT FALSE;

-- Function to auto-create story state when session is created
CREATE OR REPLACE FUNCTION state.create_session_story_state()
RETURNS TRIGGER AS $$
BEGIN
    -- Create initial story state for the session
    INSERT INTO state.story_state (campaign_id, session_id, game_time, dm_notes)
    VALUES (NEW.campaign_id, NEW.id, 'Session Start', 'New session begun.');

    -- Initialize chat tracking
    UPDATE state.sessions
    SET chat_started_at = now(), chat_last_activity = now()
    WHERE id = NEW.id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto story state creation
DROP TRIGGER IF EXISTS trg_session_story_state ON state.sessions;
CREATE TRIGGER trg_session_story_state
    AFTER INSERT ON state.sessions
    FOR EACH ROW
    EXECUTE FUNCTION state.create_session_story_state();

-- Function to archive session before deletion
CREATE OR REPLACE FUNCTION state.archive_session_on_delete()
RETURNS TRIGGER AS $$
DECLARE
    chat_log JSONB;
    story_snapshot JSONB;
BEGIN
    -- Gather chat history from ledger (using session_ledger table)
    SELECT COALESCE(jsonb_agg(
        jsonb_build_object(
            'timestamp', sl.created_at,
            'event_type', sl.type,
            'payload', sl.payload,
            'speaker', sl.sender_principal_id
        ) ORDER BY sl.created_at
    ), '[]'::jsonb)
    INTO chat_log
    FROM ledger.session_ledger sl
    WHERE sl.session_id = OLD.id
    AND sl.type IN ('CHAT', 'ACTION', 'NARRATION', 'SYSTEM');

    -- Get final story state
    SELECT jsonb_build_object(
        'current_location', ss.current_location,
        'game_time', ss.game_time,
        'active_npcs', ss.active_npcs,
        'active_quests', ss.active_quests,
        'recent_events', ss.recent_events,
        'dm_notes', ss.dm_notes
    )
    INTO story_snapshot
    FROM state.story_state ss
    WHERE ss.session_id = OLD.id
    LIMIT 1;

    -- Create archive record
    INSERT INTO state.session_archives (
        original_session_id, campaign_id, session_name, session_number,
        started_at, ended_at, chat_history, final_story_state, archive_reason
    ) VALUES (
        OLD.id, OLD.campaign_id, OLD.name, OLD.session_number,
        OLD.started_at, OLD.ended_at, chat_log, COALESCE(story_snapshot, '{}'),
        'DELETED'
    );

    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for session archival
DROP TRIGGER IF EXISTS trg_archive_session ON state.sessions;
CREATE TRIGGER trg_archive_session
    BEFORE DELETE ON state.sessions
    FOR EACH ROW
    EXECUTE FUNCTION state.archive_session_on_delete();

-- Create story state for existing sessions that don't have one
INSERT INTO state.story_state (campaign_id, session_id, game_time, dm_notes)
SELECT s.campaign_id, s.id, 'Session Start', 'Retroactively created story state.'
FROM state.sessions s
LEFT JOIN state.story_state ss ON ss.session_id = s.id
WHERE ss.id IS NULL;
